theme = "lynx"
title = "SeesDisease"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "SeesDisease"
  headline = "Krankheiten ergreifen, mit SeesDisease begreifen!"
  image = "logo_notext.jpg"
  links = [
    { microscope = { href = "http://disease.local:5001", text = "Mikroskop Demonstration (Gastnetzwerk)", icon="noun-microscope-490709" } },
    {normal = { href = "https://seesdisease-demo.streamlit.app/", text = "Analyse-Tools", icon = "image-fill"} },
    { normal = { href = "https://seesdisease.com", text = "SeesDisease Dokumentation", icon = "file-earmark-text-fill" } },
    { normal = { href = "mailto:lorenzrutkevich@gmail.com", text = "Kontakt: Lorenz Rutkevich", icon = "envelope-at-fill" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true